#NOTE: Change your docker_id in image: <docker_ID>/products

#Command to run:
#docker-compose build
#docker-compose up -d

version: "3.8"

services:
  #################################
  # Products
  #################################
  products:
    build:
      context: ./
      dockerfile: api/products/Dockerfile
    image: marcsoh/products
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - config.env
    ports:
      - "5005:5005"
  #################################
  # Cart
  #################################

  cart:
    build:
      context: ./
      dockerfile: api/cart/cart.Dockerfile
    image: marcsoh/cart
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - config.env
    ports:
      - "5001:5001"

  #################################
  # Orders
  #################################
  orders:
    build:
      context: ./
      dockerfile: api/orders/orders.Dockerfile
    image: haziqilham/orders
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - config.env
    ports:
      - "5010:5010"
